package de.robinrehbein.birdy

import kotlinx.io.buffered
import kotlinx.io.files.Path
import kotlinx.io.files.SystemFileSystem
import kotlinx.io.readString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement

/**
 * Loads golden fixtures from docs/native/golden (generated by the scripts in scripts/native-golden from the
 * JS reference). Tests run with the shared module dir as working directory.
 */
object Golden {
    private val dir = Path("../../docs/native/golden")

    fun text(name: String): String = SystemFileSystem.source(Path(dir, name)).buffered().use { it.readString() }

    fun json(name: String): JsonElement = Json.parseToJsonElement(text(name))
}
