package de.robinrehbein.birdy.meta

import de.robinrehbein.birdy.platform.FakeClock
import de.robinrehbein.birdy.platform.LocalDay
import de.robinrehbein.birdy.platform.MemoryKeyValueStore
import de.robinrehbein.birdy.platform.StorageKeys
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Reproduces every scenario in docs/native/golden/meta-progress-load.json (generated by actually
 * running progress.js) against [LocalProgressRepository], scenario inputs copied 1:1 from
 * scripts/native-golden/meta-progress-load.mjs.
 */
class ProgressLoadGoldenTest {
    private fun repo(progressJson: String? = null, legacyBest: String? = null, clock: FakeClock = FakeClock()): LocalProgressRepository {
        val initial = buildMap {
            progressJson?.let { put(StorageKeys.PROGRESS, it) }
            legacyBest?.let { put(StorageKeys.LEGACY_BEST, it) }
        }
        return LocalProgressRepository(MemoryKeyValueStore(initial), clock)
    }

    @Test
    fun freshInstall() {
        val r = repo()
        val d = r.data.value
        assertEquals(0, d.coins); assertEquals(0, d.best); assertEquals(0, d.runs)
        assertEquals("sunny", r.equipped(Kind.Skin).id)
        assertEquals("none", r.equipped(Kind.Trail).id)
        assertFalse(r.owns(Kind.Skin, "sky"))
        assertFalse(d.tutorialDone)
        assertEquals(3, r.rewardedAdsLeft)
    }

    @Test
    fun legacyPreShopSaveMigration() {
        val json = """{"coins":250,"best":12,"runs":4,"owned":["sunny","sky"],"skin":"sky","trails":["none","sparkle"],"trail":"sparkle"}"""
        val r = repo(json)
        assertEquals(250, r.data.value.coins)
        assertEquals("sky", r.equipped(Kind.Skin).id)
        assertEquals("sparkle", r.equipped(Kind.Trail).id)
        assertTrue(r.permanentlyOwns(Kind.Skin, "sky"))
        assertTrue(r.permanentlyOwns(Kind.Trail, "sparkle"))
    }

    @Test
    fun birdyBestLegacyKeyMigration() {
        val r = repo("""{"coins":10,"best":3,"runs":1}""", legacyBest = "77")
        assertEquals(77, r.data.value.best)
    }

    @Test
    fun equipPointsToUnownedItemFallsBackToFree() {
        val r = repo("""{"coins":0,"items":{"skin":["sunny"]},"equip":{"skin":"doesnotexist"}}""")
        assertEquals("sunny", r.equipped(Kind.Skin).id)
    }

    @Test
    fun stylePassTrialAccess() {
        val clock = FakeClock(millis = 1_000_000L)
        val r = repo("""{"coins":0,"stylePassUntil":${clock.millis + 3_600_000L}}""", clock = clock)
        assertTrue(r.owns(Kind.Skin, "night"))
        assertTrue(r.owns(Kind.World, "candy"))
        assertFalse(r.owns(Kind.Pattern, "mask"))
        assertFalse(r.owns(Kind.Pipe, "gold"))
        assertEquals(60, r.stylePassMinutesLeft)
    }

    @Test
    fun paidProductOwnership() {
        val r = repo("""{"coins":0,"paidProducts":["birdy_skin_gold","birdy_world_candy"]}""")
        assertTrue(r.permanentlyOwns(Kind.Skin, "gold"))
        assertTrue(r.permanentlyOwns(Kind.World, "candy"))
        assertEquals("sunny", r.equipped(Kind.Skin).id)
    }

    @Test
    fun buySelectUpgradeFlow() {
        val r = repo("""{"coins":1000}""")
        assertTrue(r.buy(Kind.Skin, "sky"))
        assertEquals(900, r.data.value.coins)
        assertTrue(r.select(Kind.Skin, "sky"))
        assertFalse(r.buy(Kind.Skin, "sky"))
        assertEquals(300, r.upgradePrice("star"))
        r.buyUpgrade("star")
        assertEquals(1, r.level("star"))
        assertEquals(800, r.upgradePrice("star"))
    }

    @Test
    fun insufficientCoins() {
        val r = repo("""{"coins":5}""")
        assertFalse(r.buy(Kind.Skin, "sky"))
        assertEquals(5, r.data.value.coins)
        assertFalse(r.buyUpgrade("star"))
    }

    @Test
    fun rewardedAdCap3PerDay() {
        val r = repo("""{"coins":0}""")
        val grants = (1..5).map { r.grantRewardedCoins() }
        assertEquals(listOf(30, 30, 30, 0, 0), grants)
        assertEquals(90, r.data.value.coins)
        assertEquals(0, r.rewardedAdsLeft)
    }

    @Test
    fun claimGiftSameDayBlocked() {
        val r = repo("""{"coins":0}""")
        val first = r.claimGift()
        assertEquals(GiftClaim(20, 1), first)
        assertNull(r.claimGift())
        assertEquals(1, r.streak)
    }

    @Test
    fun finishRunCompletesEverythingWithAHugeRun() {
        val clock = FakeClock(day = LocalDay(2026, 9, 28))
        val r = repo("""{"coins":0,"best":0}""", clock = clock)
        val before = r.missions()
        assertEquals(listOf("runs" to 3, "score" to 7, "coins" to 70), before.map { it.id to it.goal })

        val run = RunStats(score = 999, coins = 50, zone = 5, bestChain = 20, powerups = 10, near = 20, plants = 200)
        val result = r.finishRun(run)

        assertTrue(result.isBest)
        assertEquals(listOf("score"), result.completed.map { it.id })
        assertEquals(
            listOf(
                "score10", "score25", "score50", "score100", "zone4", "near10", "chain5", "powers3", "plants25",
                "rareToadstool", "rareWater", "rareDiamond", "rareGalaxy",
            ),
            result.achievements.map { it.id },
        )
        assertEquals(1510, r.data.value.coins)
        assertEquals(999, r.data.value.best)
    }
}
